format = """
$username\
$directory\
$git_branch$git_state$git_status \
$cmd_duration\
$line_break\
$jobs\
$character"""

right_format = """$kubernetes$go$rust$lua"""

[directory]
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1
style = "blue"

[kubernetes]
format = '[$symbol$context ]($style)'
disabled=false

[username]
format = '[$user: ]($style)'
style_user = "bold #eb6f92"

[character]
success_symbol = "[:;](bold green)"
error_symbol = "[:;](bold red)"

[jobs]
symbol = '✦ '
number_threshold = 2
symbol_threshold = 1

[lua]
format = "[$symbol($version )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = " "

[c]
format = "[$symbol($version )]($style)"
symbol = " "

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[git_branch]
format = "[$branch]($style)"
symbol = " "
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_status]
#format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
format = "[([*$conflicted$untracked$modified](218) $ahead_behind$stashed)]($style) "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
